/*
XingChen 开放接口定义

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xingchen

import (
	"encoding/json"
)

// checks if the SysReminderRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SysReminderRequest{}

// SysReminderRequest 系统提醒参数
type SysReminderRequest struct {
	GatewayAddContent *GatewayIssuedParams `json:"gatewayAddContent,omitempty"`
	// 角色ID
	CharacterId string `json:"characterId"`
	// 聊天室ID
	ChatRoomId *int64 `json:"chatRoomId,omitempty"`
	// 系统提醒内容
	Content string `json:"content"`
	// 业务系统ID
	BizUserId            string `json:"bizUserId"`
	AdditionalProperties map[string]interface{}
}

type _SysReminderRequest SysReminderRequest

// NewSysReminderRequest instantiates a new SysReminderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSysReminderRequest(characterId string, content string, bizUserId string) *SysReminderRequest {
	this := SysReminderRequest{}
	this.CharacterId = characterId
	this.Content = content
	this.BizUserId = bizUserId
	return &this
}

// NewSysReminderRequestWithDefaults instantiates a new SysReminderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSysReminderRequestWithDefaults() *SysReminderRequest {
	this := SysReminderRequest{}
	return &this
}

// GetGatewayAddContent returns the GatewayAddContent field value if set, zero value otherwise.
func (o *SysReminderRequest) GetGatewayAddContent() GatewayIssuedParams {
	if o == nil || IsNil(o.GatewayAddContent) {
		var ret GatewayIssuedParams
		return ret
	}
	return *o.GatewayAddContent
}

// GetGatewayAddContentOk returns a tuple with the GatewayAddContent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SysReminderRequest) GetGatewayAddContentOk() (*GatewayIssuedParams, bool) {
	if o == nil || IsNil(o.GatewayAddContent) {
		return nil, false
	}
	return o.GatewayAddContent, true
}

// HasGatewayAddContent returns a boolean if a field has been set.
func (o *SysReminderRequest) HasGatewayAddContent() bool {
	if o != nil && !IsNil(o.GatewayAddContent) {
		return true
	}

	return false
}

// SetGatewayAddContent gets a reference to the given GatewayIssuedParams and assigns it to the GatewayAddContent field.
func (o *SysReminderRequest) SetGatewayAddContent(v GatewayIssuedParams) {
	o.GatewayAddContent = &v
}

// GetCharacterId returns the CharacterId field value
func (o *SysReminderRequest) GetCharacterId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CharacterId
}

// GetCharacterIdOk returns a tuple with the CharacterId field value
// and a boolean to check if the value has been set.
func (o *SysReminderRequest) GetCharacterIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CharacterId, true
}

// SetCharacterId sets field value
func (o *SysReminderRequest) SetCharacterId(v string) {
	o.CharacterId = v
}

// GetChatRoomId returns the ChatRoomId field value if set, zero value otherwise.
func (o *SysReminderRequest) GetChatRoomId() int64 {
	if o == nil || IsNil(o.ChatRoomId) {
		var ret int64
		return ret
	}
	return *o.ChatRoomId
}

// GetChatRoomIdOk returns a tuple with the ChatRoomId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SysReminderRequest) GetChatRoomIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ChatRoomId) {
		return nil, false
	}
	return o.ChatRoomId, true
}

// HasChatRoomId returns a boolean if a field has been set.
func (o *SysReminderRequest) HasChatRoomId() bool {
	if o != nil && !IsNil(o.ChatRoomId) {
		return true
	}

	return false
}

// SetChatRoomId gets a reference to the given int64 and assigns it to the ChatRoomId field.
func (o *SysReminderRequest) SetChatRoomId(v int64) {
	o.ChatRoomId = &v
}

// GetContent returns the Content field value
func (o *SysReminderRequest) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *SysReminderRequest) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *SysReminderRequest) SetContent(v string) {
	o.Content = v
}

// GetBizUserId returns the BizUserId field value
func (o *SysReminderRequest) GetBizUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BizUserId
}

// GetBizUserIdOk returns a tuple with the BizUserId field value
// and a boolean to check if the value has been set.
func (o *SysReminderRequest) GetBizUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BizUserId, true
}

// SetBizUserId sets field value
func (o *SysReminderRequest) SetBizUserId(v string) {
	o.BizUserId = v
}

func (o SysReminderRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SysReminderRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GatewayAddContent) {
		toSerialize["gatewayAddContent"] = o.GatewayAddContent
	}
	toSerialize["characterId"] = o.CharacterId
	if !IsNil(o.ChatRoomId) {
		toSerialize["chatRoomId"] = o.ChatRoomId
	}
	toSerialize["content"] = o.Content
	toSerialize["bizUserId"] = o.BizUserId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SysReminderRequest) UnmarshalJSON(bytes []byte) (err error) {
	varSysReminderRequest := _SysReminderRequest{}

	err = json.Unmarshal(bytes, &varSysReminderRequest)

	if err != nil {
		return err
	}

	*o = SysReminderRequest(varSysReminderRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "gatewayAddContent")
		delete(additionalProperties, "characterId")
		delete(additionalProperties, "chatRoomId")
		delete(additionalProperties, "content")
		delete(additionalProperties, "bizUserId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSysReminderRequest struct {
	value *SysReminderRequest
	isSet bool
}

func (v NullableSysReminderRequest) Get() *SysReminderRequest {
	return v.value
}

func (v *NullableSysReminderRequest) Set(val *SysReminderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSysReminderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSysReminderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSysReminderRequest(val *SysReminderRequest) *NullableSysReminderRequest {
	return &NullableSysReminderRequest{value: val, isSet: true}
}

func (v NullableSysReminderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSysReminderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
