/*
XingChen 开放接口定义

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xingchen

import (
	"encoding/json"
)

// checks if the CharacterKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CharacterKey{}

// CharacterKey struct for CharacterKey
type CharacterKey struct {
	CharacterId          *string `json:"characterId,omitempty"`
	Version              *int32  `json:"version,omitempty"`
	Name                 *string `json:"name,omitempty"`
	Content              *string `json:"content,omitempty"`
	Type                 *string `json:"type,omitempty"`
	Traits               *string `json:"traits,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CharacterKey CharacterKey

// NewCharacterKey instantiates a new CharacterKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCharacterKey() *CharacterKey {
	this := CharacterKey{}
	return &this
}

// NewCharacterKeyWithDefaults instantiates a new CharacterKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCharacterKeyWithDefaults() *CharacterKey {
	this := CharacterKey{}
	return &this
}

// GetCharacterId returns the CharacterId field value if set, zero value otherwise.
func (o *CharacterKey) GetCharacterId() string {
	if o == nil || IsNil(o.CharacterId) {
		var ret string
		return ret
	}
	return *o.CharacterId
}

// GetCharacterIdOk returns a tuple with the CharacterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CharacterKey) GetCharacterIdOk() (*string, bool) {
	if o == nil || IsNil(o.CharacterId) {
		return nil, false
	}
	return o.CharacterId, true
}

// HasCharacterId returns a boolean if a field has been set.
func (o *CharacterKey) HasCharacterId() bool {
	if o != nil && !IsNil(o.CharacterId) {
		return true
	}

	return false
}

// SetCharacterId gets a reference to the given string and assigns it to the CharacterId field.
func (o *CharacterKey) SetCharacterId(v string) {
	o.CharacterId = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *CharacterKey) GetVersion() int32 {
	if o == nil || IsNil(o.Version) {
		var ret int32
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CharacterKey) GetVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *CharacterKey) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int32 and assigns it to the Version field.
func (o *CharacterKey) SetVersion(v int32) {
	o.Version = &v
}

func (o *CharacterKey) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

func (o *CharacterKey) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

func (o *CharacterKey) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

func (o *CharacterKey) SetName(v string) {
	o.Name = &v
}

func (o *CharacterKey) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

func (o *CharacterKey) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

func (o *CharacterKey) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

func (o *CharacterKey) SetContent(v string) {
	o.Content = &v
}

func (o *CharacterKey) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

func (o *CharacterKey) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

func (o *CharacterKey) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

func (o *CharacterKey) SetType(v string) {
	o.Type = &v
}

func (o *CharacterKey) GetTraits() string {
	if o == nil || IsNil(o.Traits) {
		var ret string
		return ret
	}
	return *o.Traits
}

func (o *CharacterKey) GetTraitsOk() (*string, bool) {
	if o == nil || IsNil(o.Traits) {
		return nil, false
	}
	return o.Traits, true
}

func (o *CharacterKey) HasTraits() bool {
	if o != nil && !IsNil(o.Traits) {
		return true
	}

	return false
}

func (o *CharacterKey) SetTraits(v string) {
	o.Traits = &v
}

func (o CharacterKey) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CharacterKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CharacterId) {
		toSerialize["characterId"] = o.CharacterId
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Traits) {
		toSerialize["traits"] = o.Traits
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CharacterKey) UnmarshalJSON(bytes []byte) (err error) {
	varCharacterKey := _CharacterKey{}

	err = json.Unmarshal(bytes, &varCharacterKey)

	if err != nil {
		return err
	}

	*o = CharacterKey(varCharacterKey)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "characterId")
		delete(additionalProperties, "version")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCharacterKey struct {
	value *CharacterKey
	isSet bool
}

func (v NullableCharacterKey) Get() *CharacterKey {
	return v.value
}

func (v *NullableCharacterKey) Set(val *CharacterKey) {
	v.value = val
	v.isSet = true
}

func (v NullableCharacterKey) IsSet() bool {
	return v.isSet
}

func (v *NullableCharacterKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCharacterKey(val *CharacterKey) *NullableCharacterKey {
	return &NullableCharacterKey{value: val, isSet: true}
}

func (v NullableCharacterKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCharacterKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
