/*
XingChen 开放接口定义

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xingchen

import (
	"encoding/json"
)

// checks if the CharacterQueryDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CharacterQueryDTO{}

// CharacterQueryDTO 角色查询请求对象
type CharacterQueryDTO struct {
	GatewayAddContent *GatewayIssuedParams `json:"gatewayAddContent,omitempty"`
	Where             *CharacterQueryWhere `json:"where,omitempty"`
	// 排序条件，支持的排序字段为： - modifiedTime - createTime 排序优先级按列表顺序，默认降序，如果期望升序，需要在字段后指定，如：orderBy: [\\\"gmtModified desc\\\"] （gmtModified 按降序）
	OrderBy []string `json:"orderBy,omitempty"`
	// 页码，默认为 0
	PageNum *int64 `json:"pageNum,omitempty"`
	// 页条目数，1～50，默认为 10
	PageSize             *int64 `json:"pageSize,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CharacterQueryDTO CharacterQueryDTO

// NewCharacterQueryDTO instantiates a new CharacterQueryDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCharacterQueryDTO() *CharacterQueryDTO {
	this := CharacterQueryDTO{}
	return &this
}

// NewCharacterQueryDTOWithDefaults instantiates a new CharacterQueryDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCharacterQueryDTOWithDefaults() *CharacterQueryDTO {
	this := CharacterQueryDTO{}
	return &this
}

// GetGatewayAddContent returns the GatewayAddContent field value if set, zero value otherwise.
func (o *CharacterQueryDTO) GetGatewayAddContent() GatewayIssuedParams {
	if o == nil || IsNil(o.GatewayAddContent) {
		var ret GatewayIssuedParams
		return ret
	}
	return *o.GatewayAddContent
}

// GetGatewayAddContentOk returns a tuple with the GatewayAddContent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CharacterQueryDTO) GetGatewayAddContentOk() (*GatewayIssuedParams, bool) {
	if o == nil || IsNil(o.GatewayAddContent) {
		return nil, false
	}
	return o.GatewayAddContent, true
}

// HasGatewayAddContent returns a boolean if a field has been set.
func (o *CharacterQueryDTO) HasGatewayAddContent() bool {
	if o != nil && !IsNil(o.GatewayAddContent) {
		return true
	}

	return false
}

// SetGatewayAddContent gets a reference to the given GatewayIssuedParams and assigns it to the GatewayAddContent field.
func (o *CharacterQueryDTO) SetGatewayAddContent(v GatewayIssuedParams) {
	o.GatewayAddContent = &v
}

// GetWhere returns the Where field value if set, zero value otherwise.
func (o *CharacterQueryDTO) GetWhere() CharacterQueryWhere {
	if o == nil || IsNil(o.Where) {
		var ret CharacterQueryWhere
		return ret
	}
	return *o.Where
}

// GetWhereOk returns a tuple with the Where field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CharacterQueryDTO) GetWhereOk() (*CharacterQueryWhere, bool) {
	if o == nil || IsNil(o.Where) {
		return nil, false
	}
	return o.Where, true
}

// HasWhere returns a boolean if a field has been set.
func (o *CharacterQueryDTO) HasWhere() bool {
	if o != nil && !IsNil(o.Where) {
		return true
	}

	return false
}

// SetWhere gets a reference to the given CharacterQueryWhere and assigns it to the Where field.
func (o *CharacterQueryDTO) SetWhere(v CharacterQueryWhere) {
	o.Where = &v
}

// GetOrderBy returns the OrderBy field value if set, zero value otherwise.
func (o *CharacterQueryDTO) GetOrderBy() []string {
	if o == nil || IsNil(o.OrderBy) {
		var ret []string
		return ret
	}
	return o.OrderBy
}

// GetOrderByOk returns a tuple with the OrderBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CharacterQueryDTO) GetOrderByOk() ([]string, bool) {
	if o == nil || IsNil(o.OrderBy) {
		return nil, false
	}
	return o.OrderBy, true
}

// HasOrderBy returns a boolean if a field has been set.
func (o *CharacterQueryDTO) HasOrderBy() bool {
	if o != nil && !IsNil(o.OrderBy) {
		return true
	}

	return false
}

// SetOrderBy gets a reference to the given []string and assigns it to the OrderBy field.
func (o *CharacterQueryDTO) SetOrderBy(v []string) {
	o.OrderBy = v
}

// GetPageNum returns the PageNum field value if set, zero value otherwise.
func (o *CharacterQueryDTO) GetPageNum() int64 {
	if o == nil || IsNil(o.PageNum) {
		var ret int64
		return ret
	}
	return *o.PageNum
}

// GetPageNumOk returns a tuple with the PageNum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CharacterQueryDTO) GetPageNumOk() (*int64, bool) {
	if o == nil || IsNil(o.PageNum) {
		return nil, false
	}
	return o.PageNum, true
}

// HasPageNum returns a boolean if a field has been set.
func (o *CharacterQueryDTO) HasPageNum() bool {
	if o != nil && !IsNil(o.PageNum) {
		return true
	}

	return false
}

// SetPageNum gets a reference to the given int64 and assigns it to the PageNum field.
func (o *CharacterQueryDTO) SetPageNum(v int64) {
	o.PageNum = &v
}

// GetPageSize returns the PageSize field value if set, zero value otherwise.
func (o *CharacterQueryDTO) GetPageSize() int64 {
	if o == nil || IsNil(o.PageSize) {
		var ret int64
		return ret
	}
	return *o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CharacterQueryDTO) GetPageSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.PageSize) {
		return nil, false
	}
	return o.PageSize, true
}

// HasPageSize returns a boolean if a field has been set.
func (o *CharacterQueryDTO) HasPageSize() bool {
	if o != nil && !IsNil(o.PageSize) {
		return true
	}

	return false
}

// SetPageSize gets a reference to the given int64 and assigns it to the PageSize field.
func (o *CharacterQueryDTO) SetPageSize(v int64) {
	o.PageSize = &v
}

func (o CharacterQueryDTO) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CharacterQueryDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GatewayAddContent) {
		toSerialize["gatewayAddContent"] = o.GatewayAddContent
	}
	if !IsNil(o.Where) {
		toSerialize["where"] = o.Where
	}
	if !IsNil(o.OrderBy) {
		toSerialize["orderBy"] = o.OrderBy
	}
	if !IsNil(o.PageNum) {
		toSerialize["pageNum"] = o.PageNum
	}
	if !IsNil(o.PageSize) {
		toSerialize["pageSize"] = o.PageSize
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CharacterQueryDTO) UnmarshalJSON(bytes []byte) (err error) {
	varCharacterQueryDTO := _CharacterQueryDTO{}

	err = json.Unmarshal(bytes, &varCharacterQueryDTO)

	if err != nil {
		return err
	}

	*o = CharacterQueryDTO(varCharacterQueryDTO)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "gatewayAddContent")
		delete(additionalProperties, "where")
		delete(additionalProperties, "orderBy")
		delete(additionalProperties, "pageNum")
		delete(additionalProperties, "pageSize")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCharacterQueryDTO struct {
	value *CharacterQueryDTO
	isSet bool
}

func (v NullableCharacterQueryDTO) Get() *CharacterQueryDTO {
	return v.value
}

func (v *NullableCharacterQueryDTO) Set(val *CharacterQueryDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableCharacterQueryDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableCharacterQueryDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCharacterQueryDTO(val *CharacterQueryDTO) *NullableCharacterQueryDTO {
	return &NullableCharacterQueryDTO{value: val, isSet: true}
}

func (v NullableCharacterQueryDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCharacterQueryDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
